config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'projects#index'

  resources :projects, except: :destroy do
    resources :comments
  end

  get 'signup', to: 'users#new'
  resources :users, only: [:create]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
end

app/models/active_admin_comment.rb
# frozen_string_literal: true

class ActiveAdminComment < ApplicationRecord
  has_attached_file :upload
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :project
  belongs_to :user
  validates :content, presence: true, length: { maximum: 200 }
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  has_many :comments
  has_many :status_changes
  validates :name, presence: true
  belongs_to :user

  STATUSES = %i[not_yet_started in_progress blocked done].freeze
end

app/models/status_change.rb
# frozen_string_literal: true

class StatusChange < ApplicationRecord
  belongs_to :project
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :comments

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 8 }, allow_nil: true

  has_secure_password
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def authorize
    redirect_to login_path, alert: 'You must be logged in to access this page.' unless logged_in?
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  before_action :authorize

  def create
    @comment = CommentServices::CreateComment.call(comment_params, current_user)
    if @comment.persisted?
      flash[:notice] = 'Comment was successfully created.'
    else
      flash[:error] = @comment.errors.full_messages.join(', ')
    end
    redirect_to project_path(@comment.project_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :user_id).merge(project_id: params[:project_id])
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show update destroy]
  before_action :authorize

  def index
    @projects = Project.all
  end

  def show
    @comments = CommentsQuery.new.by_project(@project).newest_first.relation
    @status_changes = StatusChangesQuery.new.by_project(@project).oldest_first.relation
  end

  def new
    @project = Project.new
  end

  def create
    @project = ProjectServices::CreateProject.call(project_params, current_user)
    if @project.persisted?
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    ProjectServices::StatusChanger.call(@project, project_params[:status], current_user)
    flash[:notice] = 'Status was successfully changed.'
    redirect_to @project
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :status, :user_id)
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  def new; end

  def create
    authenticator = SessionAuthenticator.new(params[:session][:email], params[:session][:password])
    if authenticator.authenticate
      log_in authenticator.user
      redirect_to root_url
    else
      flash.now[:error] = authenticator.error
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = UserServices::CreateUser.call(user_params)
    if @user.persisted?
      log_in @user
      redirect_to root_url
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def format_date(date)
    date.strftime('%b %d, %Y %I:%M %p')
  end
end

app/helpers/comments_helper.rb
# frozen_string_literal: true

module CommentsHelper
  def format_comment_date(date)
    date.strftime('%b %d, %Y %I:%M %p')
  end
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/views/comments/_comment.slim
li.comment-item
  p.comment-user
    strong = comment.user.name
  p.comment-content
    | #{comment.content}
  p.comment-date
    | #{format_date(comment.created_at)}

app/views/comments/_form.html.slim
label for="comment" Your Comment:
= form_with(model: [project, comment], local: true) do |form|
  = form.hidden_field :project_id, value: project.id

  .field
    = form.text_area :content, id: "comment", rows: "4", cols: "50", label: false

  button type="submit" Post Comment

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="UTF-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    header
      nav
        ul
          - if current_user.present?
            li = link_to 'Home', root_path
            li = link_to 'Projects', projects_path
            = link_to 'Log Out', logout_path, method: :delete
            li #{current_user.email}
          - else
            li = link_to 'Log In', login_path
            li = link_to 'Sign up', signup_path
    main
      section.project
        = yield

app/views/projects/_form_status.html.slim
= form_with(model: @project, local: true) do |form|
  = form.hidden_field :id, value: @project.id
  .field
    = form.select :status, Project::STATUSES

  button type="submit" Change Status

app/views/projects/_project.html.slim
li
  p
    = link_to project.name, project_path(project)
    '
    | #{project.status}

app/views/projects/_status_change.html.slim
li
  | Changed status from #{status_change.from_status} to #{status_change.to_status} on #{format_date(status_change.created_at)} by #{status_change.user.email}

app/views/projects/index.html.slim
.project-header
  h2 Projects
  a.new-project-btn href=new_project_path New project
ul
  == render partial: "projects/project", collection: @projects

app/views/projects/new.html.slim
h1 New Project

= form_with(model: @project, local: true) do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :status
    = f.select :status, Project::STATUSES

  button type="submit" Add

app/views/projects/show.html.slim
= render 'shared/flash_messages'
h2 #{@project.name} | #{@project.status}
= render "projects/form_status"

section.status-changes
  h2 Status Changes
  ul
    - if @status_changes.any?
      = render partial: "projects/status_change", collection: @status_changes  
    - else
      p No status changes found.

section.comments
h2 Comments

ul
  - if @project.comments.any?
    = render partial: "comments/comment", collection: @comments

div.comment-form
  h3 Post a Comment
  = render "comments/form", comment: Comment.new, project: @project

app/views/shared/_error_messages.html.slim
- if object.errors.any?
  .alert.alert-danger
    h4 Errors found
    ul
      - object.errors.full_messages.each do |msg|
        li = msg

app/views/shared/_flash_messages.html.slim
- if flash.now[:error]
  .alert.alert-danger
    = flash.now[:error]
- if flash.now[:notice]
  .alert.alert-success
    = flash.now[:notice]

app/views/users/new.html.slim
h1 Sign up
= form_with(model: @user, local: true) do |f|
  = render 'shared/error_messages', object: f.object
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'

  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
    
  .form-group
    = f.label :password
    = f.password_field :password, class: 'form-control'

  .form-group
    = f.label :password_confirmation
    = f.password_field :password_confirmation, class: 'form-control'

  = f.submit 'Sign up', class: 'btn btn-primary'